#!/usr/bin/env bash

echo "Updating packages..."
  sudo apt-get update && sudo apt-get upgrade -y

echo "Installing basic packages..."
  sudo apt-get install -y build-essential openssh-server libxml2 libxml2-dev libxslt1-dev libgmp-dev
  sudo apt-get install -y git git-core sqlite3 libsqlite3-dev imagemagick

echo "Installing MySQL..."
  sudo apt-get install -y mysql-server libmysqlclient-dev

echo "Installing RVM..."
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  curl -sSL https://get.rvm.io | bash -s stable --ruby

echo "Installing Terminator..."
  sudo apt-get install -y terminator

echo "Installring Redis..."
  sudo apt-get install -y redis-server

echo "Installing Node.js w/ Bower..."
  curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  sudo apt-get install -y nodejs
  mkdir ~/.npm-global
  npm config set prefix '~/.npm-global'
  export PATH=~/.npm-global/bin:$PATH
  source ~/.profile
  npm install -g bower

echo "Installing AWS..."
  sudo apt-get install -y python2.7 python-dev libxml2-dev libxslt-dev python-pip
  sudo pip install awscli
  sudo pip install awsebcli
