#!/bin/sh

# packages
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y htop build-essential git sqlite3 libsqlite3-dev memcached redis-server libxml2 libxml2-dev libxslt1-dev libgmp-dev nodejs

# mysql
debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
sudo apt-get install -y mysql-server libmysqlclient-dev

update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8

\curl -sSL https://get.rvm.io | bash -s stable --ruby
